### ISSUE TITLE
Hosting / Domain / Namespace

### ISSUE THREAD

**Issue by mro** [piccolo2d/piccolo2d.github.io#4]
I wonder if we should bug that guy on the phone: https://github.com/piccolo2d/piccolo2d.java/issues/248#issuecomment-129424235

Not responding to [emails](https://groups.google.com/d/msg/piccolo2d-dev/cAnUemVUVcw/9fDh3w_FBQAJ) isn't good for a domain admin, is it? What's the usual path here to get an email answered?

I think I'll try [snail mail](//redacted) first, however.

**Comment by mro** [comment]
I just shopped me the `piccolo2d.info` domain for 15€/year which I shall donate until 2025. I may add a [![Flattr this git repo](http://api.flattr.com/button/flattr-badge-large.png)](https://flattr.com/submit/auto?user_id=mro&url=http://piccolo2d.info&title=piccolo2d%20hosting&language=&tags=github,piccolo2d&category=software) button and in turn donate the annual surplus (if any) to fsf.org or so.

Nevertheless `.org` is used as the java namespace and maven repo base. So we should try get the `.org` back.

**Comment by heuermh** [comment]
I agree about the `.org`.

Thank you for your donation, @mro

**Comment by mro** [comment]
the phone number `<redacted>` doesn't exist. What next, ideas?

**Comment by mro** [comment]
meanwhile the whois entry has changed to another registrar - still with the same non-operational phone number:

```
Domain Name:PICCOLO2D.ORG
<redacted>
DNSSEC:Unsigned

Access to Public Interest Registry WHOIS information is provided to assist persons in
determining the contents of a domain name registration record in the Public Interest Registry
registry database. The data in this record is provided by Public Interest Registry for
informational purposes only, and Public Interest Registry does not guarantee its accuracy. This
service is intended only for query-based access. You agree that you will use this data only for
lawful purposes and that, under no circumstances will you use this data to(a) allow, enable, or
otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited,
commercial advertising or solicitations to entities other than the data recipient's own existing
customers; or (b) enable high volume, automated, electronic processes that send queries or data
to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to
register domain names or modify existing registrations. All rights reserved. Public Interest
Registry reserves the right to modify these terms at any time. By submitting this query, you
agree to abide by this policy. For more information on Whois status codes, please visit
https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en.
```

so what next to get attention, a registered letter with reply advice?

**Comment by mro** [comment]
FYI, sent a registered letter with reply advice yesterday. Took pdf from https://github.com/piccolo2d/piccolo2d.github.io/issues/4#issue-100526373

I think I'll post the reply here once I've got it. Might take up to 20 days however.

**Comment by mro** [comment]
Dear Mr. Naohiro Arita,

this is wonderful news, I am speechless!

I shall start a domain transfer request in the next hours.

Greetings from all the piccolo2d friends,

```
Marcus Rohrmoser
```

Am 09.10.2015 um 11:08 schrieb <redacted>:

> Dear Mr. Marcus Rohrmoser
> 
> I saw your letter about piccolo2d.org domain. And I am sorry I didn't notice your e-mail.
> 
> I bought this domain at domain auction site ($326.00). But I will transfer the domain back to you. Domain lock has already disabled.
> 
> Authorization Info
> <redacted>
> 
> Best regards ,
> 
> Naohiro Arita

**Comment by heuermh** [comment]
Nice work, @mro.  Thank you.

**Comment by mro** [comment]
thanks, a big thank you also goes to Mr. Naohiro Arita who handed back the domain as soon as he got notice of our request.

I suggest to send him an annual greeting post-card for the next 10 years. Who wants to start?

**Comment by mro** [comment]
Hi Google Code shutdowners,

can you please change the redirect url from http://piccolo2d.info/community.html to

  http://piccolo2d.org/community.html

Reason: Back in August when google code went readonly, we had no access to the .org domain which is both the traditional and future home of the project as well as the Java namespace. If interested see details here: https://github.com/piccolo2d/piccolo2d.github.io/issues/4#issuecomment-132192547 The .info will expire in ~10 months.

Thanks in advance,
    Marcus Rohrmoser

**Comment by mro** [comment]
Done.

Cheers,
-Chris

**Comment by mro** [comment]
just now I have removed the DNS A record of piccolo2d.org and have cancelled the domain (still paid until Oct 10th).
