### ISSUE TITLE
Website Bug

### ISSUE THREAD

**Issue by vincent456** [piccolo2d/piccolo2d.github.io#5]
Your tutorials are not working. They create java errors. The imports are wrong too. It appears that they don't match your examples (the examples work).

**Comment by heuermh** [comment]
Thanks for reporting this issue.  The tutorials at what URL?

**Comment by vincent456** [comment]
At least the http://piccolo2d.org/learn/interface.html and the http://piccolo2d.org/learn/interaction.html, I didn't checked for the rest

**Comment by mro** [comment]
having not touched java for almost a decade – what's the precise java errors produced?

**Comment by heuermh** [comment]
There is some tutorial code at
https://github.com/piccolo2d/piccolo2d.java/tree/master/examples/src/main/java/org/piccolo2d/tutorial
which is kept up to date with the code base. Unfortunately the code examples embedded in the docs aren't.
